version: "3"
services:
  web:
    build: web-code
    command: python app.py
    ports:
     - "5000:5000"
    volumes:
     - ./web-code:/code # modified here to take into account the new app path
    container_name: web
    networks:
        - redis_some-net


networks:
  redis_some-net:
    external: true